# -*- coding: utf-8 -*-
"""Python Internal Assessment 1 - Preethi R.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iWKXf9-Ei1ECRHOxJAp37CMwlA4kBi1T
"""

#1
print("AREA OF RECTANGLE")
length =int(input("Enter the length of rectangle:"))
width = int(input("Enter the width of rectangle:"))
area = length * width
print(f'Area of rectangle for length {length} and width {width} is {area}')

#2
print("BODY MASS INDEX(BMI)")
weight = int(input("Enter the weight(kg):"))
height = int(input("Enter the height(m):"))
bmi = weight/(height ** 2)
print(f'BMI is {bmi}')

#3
students = {}
while 1:
  name = str(input("Enter student name:"))
  students[name] = int(input("Enter score:"))
  ch = input("Do you need to add another student(y/n):")
  if(ch.lower()=='n'):
    break

print(students)

#4
age = int(input("Enter your age:"))
if(age<19):
  print("Minor")
elif(age>=19 and age<60):
  print("Adult")
else:
  print("Senior")

#5
for num in range(2,50,2):
  print(num)

#6
passwords = {'Preethi':'pree123', 'ABCDE':'abcde'}
username = str(input("Enter the username:"))
password = str(input("Enter the password:"))
while(passwords[username] != password):
  print("Password incorrect! Please try again.")
  password = str(input("Enter the password:"))
print("Username and password are correct!")

#7
def avg(list2):
  total = 0
  for i in range(len(list2)):
    total = total + list2[i]
  averag = total/len(list2)
  return averag


list1 = [1,2,3,4,5,6,7]
average = avg(list1)
print(f'Average is {average}')

#8
def vowels(string):
  count = 0
  vow = ['a','e','i','o','u', 'A','E','I','O','U']
  for i in range(len(string)):
    if string[i] in vow:
      count = count + 1
  return count

str1 = str(input("Enter string:"))
result = vowels(str1)
print(f'Number of vowels in {str1} is {result}')

#9
import datetime as datetime

currdate = datetime.datetime.now()
print(currdate)

#10
try:
  int1 = int(input("Enter number 1:"))
  int2 = int(input("Enter number 2:"))
  total = int1 + int2
  print(f'Total is {total}')
except:
  print("Your input should be in integer type")

#11
try:
  int1 = int(input("Enter integer:"))
except ValueError:
  print(f"Please enter integer {ValueError}")

#12
try:
  int1 = int(input("Enter the dividend:"))
  int2 = int(input("Enter the divisor:"))
  result = int1/int2
  print(f'Result is {result}')
except:
  print("Your divisor cannot be zero")

#13
write_file = open('/content/sample.txt','a')
write_file.write("Hello, Python!")
write_file.close()

#14
read_file = open('/content/sample.txt','r')
print(read_file.read())
read_file.close()

#15
write_file = open('/content/sample.txt','a')
write_file.write("I am Preethi R")
write_file.close()

read_file = open('/content/sample.txt','r')
print(read_file.read())
read_file.close()