# -*- coding: utf-8 -*-
"""LVADSUSR104_Preethi_R_Lab_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18HIVDqlESqNYdut6uo0ig56D1d0j1Py8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

df = pd.read_csv('/content/loan_approval.csv')
print(df.head())

print(df.isnull().sum())

df.drop_duplicates(inplace = True)

plt.boxplot(df[' residential_assets_value'])
plt.show()

q1=df[' residential_assets_value'].quantile(0.25)
q3=df[' residential_assets_value'].quantile(0.75)
iqr=q3-q1

low_limit=q1-(iqr*1.5)
up_limit=q3+(iqr*1.5)
df=df[(df[' residential_assets_value']>low_limit) & (df[' residential_assets_value']<up_limit)]
print(df)

print("Data description :\n", df.describe())
print("\nData Information :\n", df.info)
print("\nData Shape :\n", df.shape)
print("\nData Columns :\n", df.columns)
print(df.head())
print(df.tail())

lb=LabelEncoder()
df[' education']=lb.fit_transform(df[' education'])
df[' loan_status']=lb.fit_transform(df[' loan_status'])
df[' self_employed']=lb.fit_transform(df[' self_employed'])

x=df.drop(columns=[' loan_status','loan_id'])
y=df[' loan_status']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
mlclf=RandomForestClassifier()
fit=mlclf.fit(x_train,y_train)
op=mlclf.predict(x_test)
print(op)

print("Classification Report :\n", classification_report(y_test, op))
print("Accuracy :", accuracy_score(y_test, op))