# -*- coding: utf-8 -*-
"""LVADSUSR104_Preethi_R_Lab_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3yi3vmxB7upTD7lGVi0ram5Nej07IQk
"""

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LinearRegression

df = df = pd.read_csv('/content/auto-mpg.csv')
print(df.head())

df = df.fillna(method='ffill')
print(df.isnull().sum())

print("Any duplicates :",df.duplicated().sum())
df=df[df['horsepower']!='?']

sns.boxplot(df)
plt.show()

q1=df['acceleration'].quantile(0.25)
q3=df['acceleration'].quantile(0.75)
iqr=q3-q1

low_limit=q1-(iqr*1.5)
up_limit=q3+(iqr*1.5)
df=df[(df['acceleration']>low_limit) & (df['acceleration']<up_limit)]
print(df)

print("Data description :\n", df.describe())
print("\nData Information :\n", df.info)
print("\nData Shape :\n", df.shape)
print("\nData Columns :\n", df.columns)
print(df.head())
print(df.tail())

print(df.corr)
sns.heatmap(df.corr())
plt.show()

lb = LabelEncoder()
df['car name']=lb.fit_transform(df['car name'])

x=df.drop(columns=['model year','car name','mpg'])
y=df['mpg']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
ml=LinearRegression()
fit=ml.fit(x_train,y_train)
op=ml.predict(x_test)

print("MAE :", mean_absolute_error(op, y_test))
print("MSE :", mean_squared_error(op, y_test))
print("R2_score :", r2_score(op, y_test))