# -*- coding: utf-8 -*-
"""LVADSUSR104_Preethi R_Lab 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ccGK1ZIWvFlyKBwnjGTMHVReFpKM0ek
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/Mall_Customers.csv')
print(df.isnull().sum())
df = df.fillna(method = 'ffill')
print("\nAfter filling null values: \n", df.isnull().sum())

num_cols = ['Age', 'Annual Income (k$)', 'Spending Score (1-100)']
cat_cols = ['Gender']

num_transformer = SimpleImputer(strategy='mean')
cat_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[('num', num_transformer, num_cols),
     ('cat', cat_transformer, cat_cols)
    ])

df2 = pd.DataFrame(preprocessor.fit_transform(df))
df2.fillna(df2.mean(), inplace=True)

scaler = StandardScaler()
data_scaled = scaler.fit_transform(df2)

sns.pairplot(df2)
plt.show()

wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(data_scaled)
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss)
plt.title('Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

kmeans = KMeans(n_clusters=3, init='k-means++', random_state=42)
cluster_labels = kmeans.fit_predict(data_scaled)
df2['Cluster'] = cluster_labels


cluster_profile = df2.groupby('Cluster').mean()
print("\nCluster profile:")
print(cluster_profile)

df2['Spend_Income_Ratio'] = df2[2] / df2[1]