# -*- coding: utf-8 -*-
"""LVADSUSR104_Preethi R_Lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19CRRv-mZLFZdUxBTvqUWxBqVWrjfsS9A
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import classification_report, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/winequality-red.csv')
print(df.isnull().sum())
df = df.fillna(method = 'bfill')
df['residual sugar'] = df['residual sugar'].fillna(df['residual sugar'].mean())
print("\nAfter filling null values: \n", df.isnull().sum())

q1=df['total sulfur dioxide'].quantile(0.25)
q3=df['total sulfur dioxide'].quantile(0.75)
iqr=q3-q1

low_limit=q1-(iqr*1.5)
up_limit=q3+(iqr*1.5)
df=df[(df['total sulfur dioxide']>low_limit) & (df['total sulfur dioxide']<up_limit)]
print(df)

df['quality_assign'] = np.where(df['quality'] >= 7, 1, 0)

x = df.drop(['quality', 'quality_assign'], axis=1)
y = df['quality_assign']
df = df.drop_duplicates(inplace = True)

sns.heatmap(df['quality_assign', 'volatile acidity', 'total sulfur dioxide'] ,annot=True)
plt.show()

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled, y_train)
vop = knn.predict(x_test)

acc = accuracy_score(y_test, vop)
print("Accuracy :, ", acc)
print("Performance Report \n", classification_report(y_test, vop))